version: "3.7"

networks:

  internal:
    external: false
    name: ${PROJECT_NAME}-internal

  external:
    external: true
    name: external

services:

  mysql:
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    image: mysql:${MYSQL_VERSION}
    networks:
      - internal
      - external
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    tty: true
    volumes:
      - mysql:/var/lib/mysql

  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:${REDIS_VERSION}
    networks:
      - internal
      - external
    ports:
      - ${REDIS_EXTERNAL_PORT}:6379
    tty: true
    volumes:
      - redis:/data

  php:
    build:
      args:
        PHP_VERSION: ${PHP_VERSION}
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${PROJECT_NAME}-php
    depends_on:
      - mysql
      - redis
    environment:
      PHP_EXTENSION_BCMATH: 1
    image: ${PROJECT_NAME}-php
    networks:
      - internal
    tty: true
    volumes:
      - ./src:/var/www/html:delegated

  nginx:
    build:
      args:
        NGINX_VERSION: ${NGINX_VERSION}
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: ${PROJECT_NAME}-nginx
    depends_on:
      - mysql
      - redis
      - php
    image: ${PROJECT_NAME}-nginx
    networks:
      - internal
      - external
    ports:
      - ${NGINX_EXTERNAL_PORT}:80
    tty: true
    volumes:
      - ./src/public:/var/www/html/public:delegated

volumes:

  mysql:
    name: ${PROJECT_NAME}-mysql

  redis:
    name: ${PROJECT_NAME}-redis
